(define (make-point x y) (cons x y) )
(define (x-point p) (car p))
(define (y-point p) (cdr p))
(define (make-segment start end) (cons start end))
(define (start-segment seg) (car seg))
(define (end-segment seg) (cdr seg))
(define (midpoint-segment seg)
  (cons (/ (+ (x-point (start-segment seg))
              (x-point (end-segment seg)))
           2)
        (/ (+ (y-point (start-segment seg))
              (y-point (end-segment seg)))
           2)))
